/* Generated By:JJTree: Do not edit this line. ASTapplication.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTapplication extends SimpleNode {
  public ASTapplication(int id) {
    super(id);
  }

  public ASTapplication(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public String toString() {
      return "App";
  }
}
/* JavaCC - OriginalChecksum=fb7bcd047ec285bb45fc032f2fe2565b (do not edit this line) */
