/* Generated By:JJTree: Do not edit this line. ASTaOp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

public class ASTaOp extends SimpleNode {

    private static int ADD = 0;
    private static int SUB = 1;
    private static int DIV = 2;
    private static int MUL = 3;
    private static int APP = 4;
    private int opNum = -1;

    public ASTaOp(int id) {
        super(id);
    }

    public ASTaOp(Parser p, int id) {
        super(p, id);
    }

    public void setOp(int i) {
        opNum = i;
    }

    public int getOp() {
        return opNum;
    }

    /**
     * Accept the visitor. *
     */
    public Object jjtAccept(ParserVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    public String toString() {
        String result = "";
        switch (opNum) {
            case 0:
                result = "add";
                break;
            case 1:
                result = "sub";
                break;
            case 2:
                result = "mul";
                break;
            case 3:
                result = "div";
                break;
            case 4:
                result = "app";
                break;
        }
        return "Op: " + result;
    }
}
/* JavaCC - OriginalChecksum=ebf51d8cb05615e6f1c68b3643f3410f (do not edit this line) */
