/* Generated By:JJTree: Do not edit this line. ASTasub.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTasub extends SimpleNode {
  public ASTasub(int id) {
    super(id);
  }

  public ASTasub(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public String toString() {
      return "aSub";
  }
}
/* JavaCC - OriginalChecksum=d2a78c125c99bb796ea6351cad4450a3 (do not edit this line) */
