/* Generated By:JJTree: Do not edit this line. ASTclosure.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTclosure extends SimpleNode {
  public ASTclosure(int id) {
    super(id);
  }

  public ASTclosure(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public String toString() {
      return "Closure";
  }
}
/* JavaCC - OriginalChecksum=4ac0339e416012d8a0166c0db67c0f01 (do not edit this line) */
