/* Generated By:JJTree: Do not edit this line. ASTexpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTexpr extends SimpleNode {
  public ASTexpr(int id) {
    super(id);
  }

  public ASTexpr(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public String toString() {
      return "Expression";
  }
}
/* JavaCC - OriginalChecksum=1b6c60dba2af732d3d66033c573a6c77 (do not edit this line) */
