/* Generated By:JJTree: Do not edit this line. ASTfbody.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTfbody extends SimpleNode {
  public ASTfbody(int id) {
    super(id);
  }

  public ASTfbody(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public String toString() {
      return "Function Body";
  }
}
/* JavaCC - OriginalChecksum=4828de4623009907db6b3b2f77788abc (do not edit this line) */
