/* Generated By:JJTree: Do not edit this line. ASTMultiplication.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMultiplication extends SimpleNode {
  public ASTMultiplication(int id) {
    super(id);
  }

  public ASTMultiplication(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=19c348151c6b056a62c80cafa5c86c60 (do not edit this line) */
