/* Generated By:JJTree: Do not edit this line. ASTmtsub.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTmtsub extends SimpleNode {
  public ASTmtsub(int id) {
    super(id);
  }

  public ASTmtsub(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public String toString() {
      return "MTSUB";
  }
}
/* JavaCC - OriginalChecksum=09da404e58fcfbc6a95fdd5f77460419 (do not edit this line) */
