/* Generated By:JJTree: Do not edit this line. ASTnumexp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTnumexp extends SimpleNode {
    private static final int ADD = 0;
    private static final int SUB = 1;
    private static final int DIV = 2;
    private static final int MUL = 3;
    private static final int APP = 4;
	int opNum = -1;
  public ASTnumexp(int id) {
    super(id);
  }

  public ASTnumexp(Parser p, int id) {
    super(p, id);
  }
  public void setOp(int i)
{
opNum = i;
}

  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
    public String toString() {
	switch(opNum){      
	case ADD : return "+";
	case SUB : return "-";
	case DIV : return "/";
	case MUL : return "*";
	case APP : return "App";
	default : return "Error";
	}
}
}
/* JavaCC - OriginalChecksum=2a6de488c4b333d5abcb9ce53af48967 (do not edit this line) */
