/* Generated By:JJTree: Do not edit this line. ASTop.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTop extends SimpleNode {
    private static int ADD = 0;
    private static int SUB = 1;
    private static int DIV = 2;
    private static int MUL = 3;
    
    private int opNum = -1;
  public ASTop(int id) {
    super(id);
  }

  public ASTop(Parser p, int id) {
    super(p, id);
  }

  public void setOp(int i) {
      opNum = i;
  }
  
  public int getOp() {
      return opNum;
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public String toString() {
	switch(opNum){      
	case 0 : return "+";
	case 1 : return "-";
	case 2 : return "/";
	case 3 : return "*";
	default : return "Error";
}
  }
}
/* JavaCC - OriginalChecksum=3559814bce9d3fac7700b10b2cf846ce (do not edit this line) */
