/* Generated By:JJTree: Do not edit this line. ASTparams.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTparams extends SimpleNode {
  public ASTparams(int id) {
    super(id);
  }

  public ASTparams(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public String toString() {
      return "Function Parameters";
  }
}
/* JavaCC - OriginalChecksum=7ddfb0df2cea03019dc144abdc6e2d07 (do not edit this line) */
