/* Generated By:JJTree: Do not edit this line. ASTSubtraction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSubtraction extends SimpleNode {
  public ASTSubtraction(int id) {
    super(id);
  }

  public ASTSubtraction(Parser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9c1c286f8578aa9abf15e60ee04d4dc6 (do not edit this line) */
