/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
public interface ParserTreeConstants
{
  public int JJTNUMBER = 0;
  public int JJTSYMBOL = 1;
  public int JJTVOID = 2;
  public int JJTOP = 3;
  public int JJTAPP = 4;
  public int JJTFUNCTIONAPPLICATION = 5;
  public int JJTFUNCTION = 6;
  public int JJTAPPLICATION = 7;
  public int JJTASUB = 8;
  public int JJTMTSUB = 9;
  public int JJTCLOSURE = 10;
  public int JJTPARAMS = 11;
  public int JJTFBODY = 12;
  public int JJTEXPR = 13;
  public int JJTAOP = 14;
  public int JJTPROG = 15;


  public String[] jjtNodeName = {
    "number",
    "symbol",
    "void",
    "op",
    "App",
    "FunctionApplication",
    "Function",
    "application",
    "asub",
    "mtsub",
    "closure",
    "params",
    "fbody",
    "expr",
    "aOp",
    "prog",
  };
}
/* JavaCC - OriginalChecksum=e4dfb55d9b15ebc2b15f0b3ab1f9d36f (do not edit this line) */
