/* Generated By:JavaCC: Do not edit this line. ParserVisitor.java Version 5.0 */
public interface ParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTinteger node, Object data);
  public Object visit(ASTsymbol node, Object data);
  public Object visit(ASTAddition node, Object data);
  public Object visit(ASTSubtraction node, Object data);
  public Object visit(ASTMultiplication node, Object data);
  public Object visit(ASTDivision node, Object data);
  public Object visit(ASTFunctionApplication node, Object data);
  public Object visit(ASTFunction node, Object data);
  public Object visit(ASTprog node, Object data);
}
/* JavaCC - OriginalChecksum=53af52fb1131c7c9aacf5250b2f8bc58 (do not edit this line) */
