/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
public interface ParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTNUMBER = 1;
  public int JJTSYMBOL = 2;
  public int JJTADDITION = 3;
  public int JJTSUBTRACTION = 4;
  public int JJTMULTIPLICATION = 5;
  public int JJTDIVISION = 6;
  public int JJTFUNCTIONAPPLICATION = 7;
  public int JJTFUNCTION = 8;
  public int JJTAPPLICATION = 9;
  public int JJTASUB = 10;
  public int JJTMTSUB = 11;
  public int JJTCLOSURE = 12;
  public int JJTPARAMS = 13;
  public int JJTFBODY = 14;
  public int JJTEXPR = 15;
  public int JJTAOP = 16;
  public int JJTPROG = 17;


  public String[] jjtNodeName = {
    "void",
    "number",
    "symbol",
    "Addition",
    "Subtraction",
    "Multiplication",
    "Division",
    "FunctionApplication",
    "Function",
    "application",
    "asub",
    "mtsub",
    "closure",
    "params",
    "fbody",
    "expr",
    "aOp",
    "prog",
  };
}
/* JavaCC - OriginalChecksum=02820f5701351a18bb7f140e1385982f (do not edit this line) */
