/* Generated By:JavaCC: Do not edit this line. ParserVisitor.java Version 5.0 */
public interface ParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTnumber node, Object data);
  public Object visit(ASTsymbol node, Object data);
  public Object visit(ASTop node, Object data);
  public Object visit(ASTApp node, Object data);
  public Object visit(ASTFunctionApplication node, Object data);
  public Object visit(ASTFunction node, Object data);
  public Object visit(ASTapplication node, Object data);
  public Object visit(ASTasub node, Object data);
  public Object visit(ASTmtsub node, Object data);
  public Object visit(ASTclosure node, Object data);
  public Object visit(ASTparams node, Object data);
  public Object visit(ASTfbody node, Object data);
  public Object visit(ASTexpr node, Object data);
  public Object visit(ASTaOp node, Object data);
  public Object visit(ASTprog node, Object data);
}
/* JavaCC - OriginalChecksum=5bfa4589543df07e0dffb96c441d58b0 (do not edit this line) */
