/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NIL = 6;
  /** RegularExpression Id. */
  int LPAR = 7;
  /** RegularExpression Id. */
  int RPAR = 8;
  /** RegularExpression Id. */
  int INTEGER = 9;
  /** RegularExpression Id. */
  int LAMBDA = 10;
  /** RegularExpression Id. */
  int LET = 11;
  /** RegularExpression Id. */
  int ADD = 12;
  /** RegularExpression Id. */
  int SUB = 13;
  /** RegularExpression Id. */
  int MUL = 14;
  /** RegularExpression Id. */
  int DIV = 15;
  /** RegularExpression Id. */
  int SYMBOL = 16;
  /** RegularExpression Id. */
  int ERROR = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<NIL>",
    "\"(\"",
    "\")\"",
    "<INTEGER>",
    "\"lambda\"",
    "\"let\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "<SYMBOL>",
    "<ERROR>",
  };

}
