/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LPAR = 6;
  /** RegularExpression Id. */
  int RPAR = 7;
  /** RegularExpression Id. */
  int NUMBER = 8;
  /** RegularExpression Id. */
  int LAMBDA = 9;
  /** RegularExpression Id. */
  int LET = 10;
  /** RegularExpression Id. */
  int ADD = 11;
  /** RegularExpression Id. */
  int SUB = 12;
  /** RegularExpression Id. */
  int MUL = 13;
  /** RegularExpression Id. */
  int DIV = 14;
  /** RegularExpression Id. */
  int AADD = 15;
  /** RegularExpression Id. */
  int ASUBT = 16;
  /** RegularExpression Id. */
  int AMUL = 17;
  /** RegularExpression Id. */
  int ADIV = 18;
  /** RegularExpression Id. */
  int ASUB = 19;
  /** RegularExpression Id. */
  int CLOSURE = 20;
  /** RegularExpression Id. */
  int MTSUB = 21;
  /** RegularExpression Id. */
  int SYMBOL = 22;
  /** RegularExpression Id. */
  int ERROR = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"(\"",
    "\")\"",
    "<NUMBER>",
    "\"lambda\"",
    "\"let\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"add\"",
    "\"sub\"",
    "\"mul\"",
    "\"div\"",
    "\"aSub\"",
    "\"closure\"",
    "\"mtSub\"",
    "<SYMBOL>",
    "<ERROR>",
  };

}
