/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
public interface ParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTINTEGER = 1;
  public int JJTSYMBOL = 2;
  public int JJTADDITION = 3;
  public int JJTSUBTRACTION = 4;
  public int JJTMULTIPLICATION = 5;
  public int JJTDIVISION = 6;
  public int JJTFUNCTIONAPPLICATION = 7;
  public int JJTFUNCTION = 8;
  public int JJTPROG = 9;


  public String[] jjtNodeName = {
    "void",
    "integer",
    "symbol",
    "Addition",
    "Subtraction",
    "Multiplication",
    "Division",
    "FunctionApplication",
    "Function",
    "prog",
  };
}
/* JavaCC - OriginalChecksum=0b43a51e10d4d00f17b921a28cb9bce0 (do not edit this line) */
